version: "3.8"

name: recommendations-item-similarity-neo4j

services:
  neo4j:
    image: neo4j:5.6.0
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    volumes:
      - ./data/neo4j:/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1",
        ]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10

  recommendations:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      NEO4J_URL: neo4j://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      PORT: 3000
    depends_on:
      neo4j:
        condition: service_healthy
